### ISSUE TITLE
Increment rpc dependency to version 0.5.0

### ISSUE THREAD

**Issue by iamcharliegoddard** [dart-lang/shelf_rpc#1]
When resolving dependencies for `rpc`, `shelf_rpc` is complaining `rpc 0.5.0 does not match`:

``` bash
$ pub get
Resolving dependencies... (2.1s) 
Package rpc 0.5.0 does not match >=0.4.0 <0.5.0 derived from:
- shelf_rpc 0.0.3 depends on version >=0.4.0 <0.5.0
```

`rpc 0.5.0` is the current available version: https://pub.dartlang.org/packages/rpc.

I have coordinating issue with the rpc project: https://github.com/dart-lang/rpc/issues/45.

**Comment by wibling** [comment]
Fixed as of 6d780dc471822aad759449f217bced97f18adde2
